apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: basic-example-golang
build:
  local:
    push: false
  artifacts:
    - image: go-mod-image
      ko: {}
manifests:
  rawYaml:
    - deployment.yaml
portForward:
  - resourceType: service
    resourceName: go-mod-image
    port: 8080
