apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: basic-example-python
build:
  local:
    push: false
  artifacts:
    - image: dockerfile-image
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
